/**
 * Every word the Help Center itself shows (not the pages). To add a language, copy the `en` block under its
 * code and translate the values; any word left out falls back to English.
 *
 * "ScaleEzy" and screen or button names from the app stay in English: the app itself is in English, so a
 * reader must see the same word in the guide as on the screen.
 */
const UI = {
  en: {
    helpCenter: 'Help Center',
    helpCenterHome: 'Help Center home',
    search: 'Search the guide',
    searchHero: 'Search, e.g. "card machine" or "write off"',
    searchPlaceholder: 'What do you want to do? e.g. take a UPI payment',
    heroTitle: 'How can we help?',
    heroText: 'Simple steps for everything at the till: selling, payments, credit, returns, GST bills and closing the day.',
    startWithJob: 'Start with your job',
    browseTopics: 'Browse by topic',
    allGuides: 'All {n} guides →',
    popular: 'Popular',
    nothingMatches: 'Nothing in the guide matches',
    trySimpler: 'Try a simpler word, like UPI, return or shift.',
    toChoose: '↑ ↓ to choose',
    toOpen: 'to open',
    escClose: 'Esc to close',
    close: 'Close',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    signIn: 'Open the till',
    openApp: 'Back to the till',
    darkTheme: 'Dark theme',
    lightTheme: 'Light theme',
    language: 'Language',
    help: 'Help',
    minutes: '{n} min',
    onThisPage: 'On this page',
    tryInShop: 'Try it in your shop',
    tryOpens: 'Opens {screen} on this till.',
    trySignIn: 'Open the till to go to this screen.',
    openScreen: 'Open {screen}',
    thisScreen: 'this screen',
    previous: 'Previous',
    next: 'Next',
    notTranslated: 'This page is not in {language} yet, so it is shown in English.',
    pictureLarger: 'Picture, larger',
    boxTip: 'Tip',
    boxNote: 'Good to know',
    boxWarning: 'Careful',
    roleCashier: 'I bill at the counter',
    roleCashierText: 'Make bills, take every kind of payment, returns and exchanges.',
    roleManager: 'I run the counter',
    roleManagerText: 'Approve with your PIN, shifts and the drawer, credit and orders.',
    roleOwner: 'I own the shop',
    roleOwnerText: 'Set up the till, staff and GST, read reports, close the day.'
  },

  te: {
    helpCenter: 'సహాయ కేంద్రం',
    helpCenterHome: 'సహాయ కేంద్రం హోమ్',
    search: 'గైడ్‌లో వెతకండి',
    searchHero: 'వెతకండి, ఉదా. "డెలివరీ స్వీకరించడం"',
    searchPlaceholder: 'మీరు ఏమి చేయాలనుకుంటున్నారు? ఉదా. డెలివరీ స్వీకరించడం',
    heroTitle: 'మేము ఎలా సహాయం చేయగలం?',
    heroText: 'ScaleEzy Inventory లోని ప్రతి పనికి బొమ్మలతో సులభమైన దశలు.',
    startWithJob: 'మీ పనితో మొదలుపెట్టండి',
    browseTopics: 'విషయాల వారీగా చూడండి',
    allGuides: 'మొత్తం {n} గైడ్‌లు →',
    popular: 'ఎక్కువగా చూసినవి',
    nothingMatches: 'గైడ్‌లో ఏదీ సరిపోలలేదు',
    trySimpler: 'సేల్, స్టాక్ లేదా పాస్‌వర్డ్ వంటి సులభమైన పదంతో ప్రయత్నించండి.',
    toChoose: '↑ ↓ ఎంచుకోవడానికి',
    toOpen: 'తెరవడానికి',
    escClose: 'మూసేందుకు Esc',
    close: 'మూసివేయండి',
    openMenu: 'మెనూ తెరవండి',
    closeMenu: 'మెనూ మూసివేయండి',
    signIn: 'సైన్ ఇన్',
    openApp: 'యాప్ తెరవండి',
    darkTheme: 'డార్క్ థీమ్',
    lightTheme: 'లైట్ థీమ్',
    language: 'భాష',
    help: 'సహాయం',
    minutes: '{n} నిమి',
    onThisPage: 'ఈ పేజీలో',
    tryInShop: 'మీ షాప్‌లో ప్రయత్నించండి',
    tryOpens: 'ScaleEzy లో {screen} తెరుస్తుంది.',
    trySignIn: 'ఈ స్క్రీన్ తెరవడానికి ScaleEzy లో సైన్ ఇన్ చేయండి.',
    openScreen: '{screen} తెరవండి',
    thisScreen: 'ఈ స్క్రీన్',
    previous: 'మునుపటిది',
    next: 'తరువాతది',
    notTranslated: 'ఈ పేజీ ఇంకా {language} లో లేదు, అందుకే ఇంగ్లీష్‌లో చూపిస్తున్నాం.',
    pictureLarger: 'బొమ్మ, పెద్దగా',
    boxTip: 'చిట్కా',
    boxNote: 'తెలుసుకోండి',
    boxWarning: 'జాగ్రత్త',
    roleOwner: 'నేను షాప్ యజమాని లేదా మేనేజర్',
    roleOwnerText: 'మీ షాప్, ప్రొడక్ట్‌లు, టీమ్, సప్లయర్‌లను సెటప్ చేయండి.',
    roleSales: 'నేను కౌంటర్‌లో అమ్ముతాను',
    roleSalesText: 'వస్తువులు వెతకండి, అమ్మండి, కస్టమర్‌లను చూసుకోండి.',
    roleStock: 'నేను స్టాక్ రూమ్ చూసుకుంటాను',
    roleStockText: 'డెలివరీలు స్వీకరించండి, షెల్ఫ్‌లో పెట్టండి, తీయండి, లెక్కించండి.',
    roleBuying: 'నేను స్టాక్, కొనుగోళ్లు చూసుకుంటాను',
    roleBuyingText: 'ప్రొడక్ట్‌లు, పర్చేస్ ఆర్డర్‌లు, లెక్కింపులు, ట్రాన్స్‌ఫర్‌లు.'
  },

  hi: {
    helpCenter: 'सहायता केंद्र',
    helpCenterHome: 'सहायता केंद्र होम',
    search: 'गाइड में खोजें',
    searchHero: 'खोजें, जैसे "डिलीवरी लेना"',
    searchPlaceholder: 'आप क्या करना चाहते हैं? जैसे डिलीवरी लेना',
    heroTitle: 'हम कैसे मदद करें?',
    heroText: 'ScaleEzy Inventory के हर काम के लिए तस्वीरों के साथ आसान स्टेप।',
    startWithJob: 'अपने काम से शुरू करें',
    browseTopics: 'विषय के अनुसार देखें',
    allGuides: 'सभी {n} गाइड →',
    popular: 'लोकप्रिय',
    nothingMatches: 'गाइड में कुछ नहीं मिला',
    trySimpler: 'सेल, स्टॉक या पासवर्ड जैसा आसान शब्द आज़माएँ।',
    toChoose: '↑ ↓ चुनने के लिए',
    toOpen: 'खोलने के लिए',
    escClose: 'बंद करने के लिए Esc',
    close: 'बंद करें',
    openMenu: 'मेनू खोलें',
    closeMenu: 'मेनू बंद करें',
    signIn: 'साइन इन',
    openApp: 'ऐप खोलें',
    darkTheme: 'डार्क थीम',
    lightTheme: 'लाइट थीम',
    language: 'भाषा',
    help: 'सहायता',
    minutes: '{n} मिनट',
    onThisPage: 'इस पेज पर',
    tryInShop: 'अपनी दुकान में आज़माएँ',
    tryOpens: 'ScaleEzy में {screen} खोलता है।',
    trySignIn: 'यह स्क्रीन खोलने के लिए ScaleEzy में साइन इन करें।',
    openScreen: '{screen} खोलें',
    thisScreen: 'यह स्क्रीन',
    previous: 'पिछला',
    next: 'अगला',
    notTranslated: 'यह पेज अभी {language} में नहीं है, इसलिए अंग्रेज़ी में दिखाया गया है।',
    pictureLarger: 'तस्वीर, बड़ी',
    boxTip: 'सुझाव',
    boxNote: 'जानने लायक',
    boxWarning: 'सावधान',
    roleOwner: 'मैं दुकान का मालिक या मैनेजर हूँ',
    roleOwnerText: 'अपनी दुकान, प्रोडक्ट, टीम और सप्लायर सेट करें।',
    roleSales: 'मैं काउंटर पर बेचता/बेचती हूँ',
    roleSalesText: 'सामान खोजें, बिक्री करें, ग्राहकों का ध्यान रखें।',
    roleStock: 'मैं स्टॉक रूम संभालता/संभालती हूँ',
    roleStockText: 'डिलीवरी लें, शेल्फ पर रखें, निकालें और गिनें।',
    roleBuying: 'मैं स्टॉक और खरीद संभालता/संभालती हूँ',
    roleBuyingText: 'प्रोडक्ट, परचेज़ ऑर्डर, गिनती और ट्रांसफ़र।'
  },

  ta: {
    helpCenter: 'உதவி மையம்',
    helpCenterHome: 'உதவி மைய முகப்பு',
    search: 'வழிகாட்டியில் தேடுங்கள்',
    searchHero: 'தேடுங்கள், எ.கா. "டெலிவரியைப் பெறுதல்"',
    searchPlaceholder: 'நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்? எ.கா. டெலிவரியைப் பெறுதல்',
    heroTitle: 'நாங்கள் எப்படி உதவலாம்?',
    heroText: 'ScaleEzy Inventory-யின் ஒவ்வொரு வேலைக்கும் படங்களுடன் எளிய படிகள்.',
    startWithJob: 'உங்கள் வேலையிலிருந்து தொடங்குங்கள்',
    browseTopics: 'தலைப்பு வாரியாகப் பாருங்கள்',
    allGuides: 'அனைத்து {n} வழிகாட்டிகள் →',
    popular: 'பிரபலமானவை',
    nothingMatches: 'வழிகாட்டியில் எதுவும் பொருந்தவில்லை',
    trySimpler: 'சேல், ஸ்டாக் அல்லது பாஸ்வேர்ட் போன்ற எளிய சொல்லை முயற்சிக்கவும்.',
    toChoose: '↑ ↓ தேர்ந்தெடுக்க',
    toOpen: 'திறக்க',
    escClose: 'மூட Esc',
    close: 'மூடு',
    openMenu: 'மெனுவைத் திற',
    closeMenu: 'மெனுவை மூடு',
    signIn: 'உள்நுழை',
    openApp: 'ஆப்பைத் திற',
    darkTheme: 'டார்க் தீம்',
    lightTheme: 'லைட் தீம்',
    language: 'மொழி',
    help: 'உதவி',
    minutes: '{n} நிமி',
    onThisPage: 'இந்தப் பக்கத்தில்',
    tryInShop: 'உங்கள் கடையில் முயற்சிக்கவும்',
    tryOpens: 'ScaleEzy-யில் {screen} திறக்கும்.',
    trySignIn: 'இந்தத் திரையைத் திறக்க ScaleEzy-யில் உள்நுழையவும்.',
    openScreen: '{screen} திற',
    thisScreen: 'இந்தத் திரை',
    previous: 'முந்தையது',
    next: 'அடுத்தது',
    notTranslated: 'இந்தப் பக்கம் இன்னும் {language}-இல் இல்லை, அதனால் ஆங்கிலத்தில் காட்டப்படுகிறது.',
    pictureLarger: 'படம், பெரிதாக',
    boxTip: 'குறிப்பு',
    boxNote: 'தெரிந்துகொள்ளுங்கள்',
    boxWarning: 'கவனம்',
    roleOwner: 'நான் கடை உரிமையாளர் அல்லது மேலாளர்',
    roleOwnerText: 'உங்கள் கடை, பொருட்கள், குழு, சப்ளையர்களை அமையுங்கள்.',
    roleSales: 'நான் கவுண்டரில் விற்கிறேன்',
    roleSalesText: 'பொருட்களைத் தேடுங்கள், விற்பனை செய்யுங்கள், வாடிக்கையாளர்களைக் கவனியுங்கள்.',
    roleStock: 'நான் ஸ்டாக் அறையை நிர்வகிக்கிறேன்',
    roleStockText: 'டெலிவரிகளைப் பெறுங்கள், அலமாரியில் வையுங்கள், எடுங்கள், எண்ணுங்கள்.',
    roleBuying: 'நான் ஸ்டாக் மற்றும் கொள்முதலைக் கவனிக்கிறேன்',
    roleBuyingText: 'பொருட்கள், பர்சேஸ் ஆர்டர்கள், எண்ணிக்கைகள், டிரான்ஸ்ஃபர்கள்.'
  },

  kn: {
    helpCenter: 'ಸಹಾಯ ಕೇಂದ್ರ',
    helpCenterHome: 'ಸಹಾಯ ಕೇಂದ್ರದ ಮುಖಪುಟ',
    search: 'ಗೈಡ್‌ನಲ್ಲಿ ಹುಡುಕಿ',
    searchHero: 'ಹುಡುಕಿ, ಉದಾ. "ಡೆಲಿವರಿ ಸ್ವೀಕರಿಸುವುದು"',
    searchPlaceholder: 'ನೀವು ಏನು ಮಾಡಬೇಕು? ಉದಾ. ಡೆಲಿವರಿ ಸ್ವೀಕರಿಸುವುದು',
    heroTitle: 'ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    heroText: 'ScaleEzy Inventory ಯ ಪ್ರತಿಯೊಂದು ಕೆಲಸಕ್ಕೂ ಚಿತ್ರಗಳೊಂದಿಗೆ ಸರಳ ಹಂತಗಳು.',
    startWithJob: 'ನಿಮ್ಮ ಕೆಲಸದಿಂದ ಆರಂಭಿಸಿ',
    browseTopics: 'ವಿಷಯವಾರು ನೋಡಿ',
    allGuides: 'ಎಲ್ಲಾ {n} ಗೈಡ್‌ಗಳು →',
    popular: 'ಜನಪ್ರಿಯ',
    nothingMatches: 'ಗೈಡ್‌ನಲ್ಲಿ ಯಾವುದೂ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ',
    trySimpler: 'ಸೇಲ್, ಸ್ಟಾಕ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್‌ನಂತಹ ಸರಳ ಪದ ಬಳಸಿ ನೋಡಿ.',
    toChoose: '↑ ↓ ಆಯ್ಕೆ ಮಾಡಲು',
    toOpen: 'ತೆರೆಯಲು',
    escClose: 'ಮುಚ್ಚಲು Esc',
    close: 'ಮುಚ್ಚಿ',
    openMenu: 'ಮೆನು ತೆರೆಯಿರಿ',
    closeMenu: 'ಮೆನು ಮುಚ್ಚಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    openApp: 'ಆಪ್ ತೆರೆಯಿರಿ',
    darkTheme: 'ಡಾರ್ಕ್ ಥೀಮ್',
    lightTheme: 'ಲೈಟ್ ಥೀಮ್',
    language: 'ಭಾಷೆ',
    help: 'ಸಹಾಯ',
    minutes: '{n} ನಿಮಿ',
    onThisPage: 'ಈ ಪುಟದಲ್ಲಿ',
    tryInShop: 'ನಿಮ್ಮ ಅಂಗಡಿಯಲ್ಲಿ ಪ್ರಯತ್ನಿಸಿ',
    tryOpens: 'ScaleEzy ಯಲ್ಲಿ {screen} ತೆರೆಯುತ್ತದೆ.',
    trySignIn: 'ಈ ಸ್ಕ್ರೀನ್ ತೆರೆಯಲು ScaleEzy ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    openScreen: '{screen} ತೆರೆಯಿರಿ',
    thisScreen: 'ಈ ಸ್ಕ್ರೀನ್',
    previous: 'ಹಿಂದಿನದು',
    next: 'ಮುಂದಿನದು',
    notTranslated: 'ಈ ಪುಟ ಇನ್ನೂ {language} ನಲ್ಲಿ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ.',
    pictureLarger: 'ಚಿತ್ರ, ದೊಡ್ಡದಾಗಿ',
    boxTip: 'ಸಲಹೆ',
    boxNote: 'ತಿಳಿದಿರಲಿ',
    boxWarning: 'ಎಚ್ಚರಿಕೆ',
    roleOwner: 'ನಾನು ಅಂಗಡಿಯ ಮಾಲೀಕ ಅಥವಾ ಮ್ಯಾನೇಜರ್',
    roleOwnerText: 'ನಿಮ್ಮ ಅಂಗಡಿ, ಪ್ರಾಡಕ್ಟ್‌ಗಳು, ತಂಡ ಮತ್ತು ಸಪ್ಲೈಯರ್‌ಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಿ.',
    roleSales: 'ನಾನು ಕೌಂಟರ್‌ನಲ್ಲಿ ಮಾರಾಟ ಮಾಡುತ್ತೇನೆ',
    roleSalesText: 'ವಸ್ತುಗಳನ್ನು ಹುಡುಕಿ, ಮಾರಾಟ ಮಾಡಿ, ಗ್ರಾಹಕರನ್ನು ನೋಡಿಕೊಳ್ಳಿ.',
    roleStock: 'ನಾನು ಸ್ಟಾಕ್ ರೂಮ್ ನೋಡಿಕೊಳ್ಳುತ್ತೇನೆ',
    roleStockText: 'ಡೆಲಿವರಿ ಸ್ವೀಕರಿಸಿ, ಶೆಲ್ಫ್‌ನಲ್ಲಿ ಇಡಿ, ತೆಗೆಯಿರಿ ಮತ್ತು ಎಣಿಸಿ.',
    roleBuying: 'ನಾನು ಸ್ಟಾಕ್ ಮತ್ತು ಖರೀದಿ ನೋಡಿಕೊಳ್ಳುತ್ತೇನೆ',
    roleBuyingText: 'ಪ್ರಾಡಕ್ಟ್‌ಗಳು, ಪರ್ಚೇಸ್ ಆರ್ಡರ್‌ಗಳು, ಎಣಿಕೆಗಳು ಮತ್ತು ಟ್ರಾನ್ಸ್‌ಫರ್‌ಗಳು.'
  }
};

export function t(lang, key, vars = {}) {
  const text = UI[lang]?.[key] ?? UI.en[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ''));
}
